name: Deploy Node.js project to Azure Function App

on:
  push:
    branches:
      - dev
      - main
env:
  AZURE_FUNCTIONAPP_NAME: 'pohlmanproteanfuncapp'  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       
  NODE_VERSION: '20.x'

jobs:

  execute-code-quality-validation:
    uses: ./.github/workflows/validate.yml
    with:
      eslint-enable: true
      unit-test-enable: true
    secrets:
      token: ${{ secrets.GH_TOKEN }}

  execute-release:
    needs: execute-code-quality-validation
    uses: ./.github/workflows/release.yml
    with:
      branches: "${{ github.ref_name }}"
      slack_enabled: true
    secrets:
      token: ${{ secrets.GH_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  build-and-deploy:
    needs: execute-code-quality-validation
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}


